# The board uses a ESP32-S3 with a 16MB QSPI Flash and a 8MB QSPI PSRAM
FLASH_SIZE ?= 4
# FLASH_FREQ ?= 40m
# FLASH_MODE ?= dio

PORT_LINUX ?= /dev/ttyACM0

OPENOCD_CONFIG ?= board/esp32s3-builtin.cfg

include $(RIOTBOARD)/common/esp32s3/Makefile.include
